parent p to uppercase
This was causing in Excel 2016:
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library.Range instance at 0x1598538151048>' object has no attribute 'parent'.

This fixes the aforementioned bug